#ifndef MICVISION_LOCATION_COMMANDS_H_
#define MICVISION_LOCATION_COMMANDS_H_

#define LOCATION_SERVICE   "StartLocation"
#define LOCATION_ACTION    "Location"

#endif  // end MICVISION_LOCATION_COMMANDS_H_
